import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/navbar/Navbar";
import Categories from "@/shared/navbar/Categories"; 
import Marquee from "@/shared/navbar/Marquee";
import { Suspense } from "react";

const notoSerifBengali = Noto_Serif_Bengali({

  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className}   h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Navbar />
        <Suspense fallback={<div>Loading...</div>}>
          <Categories /> 
          <Marquee />
        </Suspense>
        {children}

      </body>
    </html>
  );
}
